### ISSUE TITLE
CSM setup should fail with proper error/exception if provisioner API fails

### ISSUE THREAD

**Issue by ajaysrivas** [Seagate/cortx-manager#215]
If failed to get setup info from provisioner, raise an exception.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~720600] [~934748] [~930816]

If this is about the CSM API, can we say this is functional today?

**Comment by hessio** [comment]
I believe this issue is no longer relevant, closing as a result.

**Comment by cortx-admin** [comment]
> Soniya Moholkar commented in Jira Server:

Provisioner API is not being used hence closing the ticket

**Comment by cortx-admin** [comment]
> Soniya Moholkar commented in Jira Server:

Verified
