### ISSUE TITLE
ContributingToCortxManager.md is not accessible. 

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-manager#276]
On https://github.com/Seagate/cortx-manager/blob/main/CORTXManagerQuickstartGuide.md#12-Install-Cortx-Manager page
at `Install OVA and these prerequisites to skip manual installation. section`  [Contributing to CORTX Manager](https://github.com/Seagate/cortx-manager/blob/main/ContributingToCortxManager.md) link is not working. 

It redirecting to https://github.com/Seagate/cortx-manager/blob/main/ContributingToCortxManager.md which is not accessible.

**Comment by Saumya-Sunder** [comment]
Resolved here https://github.com/Saumya-Sunder/cortx-manager/blob/patch-3/CORTXManagerQuickstartGuide.md

**Comment by Saumya-Sunder** [comment]
Done here https://github.com/Seagate/cortx-manager/pull/277

**Comment by shailesh-vaidya** [comment]
@Saumya-Sunder  - I observed that `Before you begin` section seems to be empty.  Actually I was trying to reproduce https://github.com/Seagate/cortx/issues/424

**Comment by johnbent** [comment]
@shailesh-vaidya , I think this is resolved so I’m closing.  Please re-open if necessary.  Thanks.

**Comment by shailesh-vaidya** [comment]
@johnbent  - I still could not access  https://github.com/Seagate/cortx-manager/blob/main/ContributingToCortxManager.md link  from the line - Refer to the Contributing to CORTX Manager document to install GitHub and clone cortx-manager and its dependent repos. @Saumya-Sunder  Mentioned that this will be taken care in https://github.com/Seagate/cortx-manager/pull/277 

@Saumya-Sunder  Could you please get https://github.com/Seagate/cortx-manager/pull/277 merged.
