### ISSUE TITLE
GUI: 'manual onboarding tasks in settings' can not be performed 

### ISSUE THREAD

**Issue by korenlev** [Seagate/cortx-manager#290]
per https://github.com/Seagate/cortx/blob/main/doc/Preboarding_and_Onboarding.rst
if someone is coming back to GUI after preboarding but before onboarding, using 'Settings' 'manually' does not work :(error - '..did not perform onboarding' and any change applied is not accepted,

**Comment by kupranay** [comment]
@korenlev  thank for raising this issue
If onboarding steps are not completed user will not be able to change any settings. @Saumya-Sunder  Lets review the documentation again

**Comment by johnbent** [comment]
Thanks @kupranay , can you please propose what language should be added and where in the document it should be added?

**Comment by Saumya-Sunder** [comment]
Issue resolved here https://github.com/Seagate/cortx/pull/523. @kupranay can you please close this issue as I do not have the rights to close issues.

**Comment by mukul-seagate11** [comment]
@all, as the issue has been addressed so closing the same
