### ISSUE TITLE
lyve pilot registration does not attach to correct S3 URL

### ISSUE THREAD

**Issue by korenlev** [Seagate/cortx-manager#291]
while cortx-GUI used to https://VM-IP:28100 , the registration process is trying (and failing ofc) to connect to 127.0.0.1:5000 for creating the new S3 account, suggest it should get the same $VM-IP from the browser

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~720600] [~934748]

Is this relevant any longer?

**Comment by hessio** [comment]
Hi @kupranay I believe we can close this issue? Please close if you no longer feel the need for this issue to be open.

**Comment by kupranay** [comment]
UDX registration and GUI is not supported in the latest release hence closing this.

**Comment by cortx-admin** [comment]
> Soniya Moholkar commented in Jira Server:

Project Canceled

**Comment by cortx-admin** [comment]
> Soniya Moholkar commented in Jira Server:

Project Canceled

**Comment by cortx-admin** [comment]
> Pranay Kumar commented in Jira Server:

Closing as in stale state from long time
