### ISSUE TITLE
Document Management API

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-manager#329]
"CSM (CORTX Management) Swagger is available at https://<management_IP>:28100/api-docs"

This needs to be added to documentation somewhere in this repo.  Also should be added to documentation in the parent repo.

**Comment by johnbent** [comment]
Thanks to @kupranay for helping get this documented.  More information:
Curl for the same
curl -X GET "https://<mgmt-ip>:28100/api/v1/stats?metric=throughput.read.mb&from=1607481696&to=1607481711&total_sample=1" -H "accept: application/json" -H "authorization: Bearer 379465a0940442d1998b14c36100a56f"

Which produces this URL:
https://<mgmt_ip>:28100/api/v1/stats?metric=throughput.read.mb&from=1607481696&to=1607481711&total_sample=1

Which gets this output:
![image](https://user-images.githubusercontent.com/2047294/101654972-55ddae80-39fe-11eb-9f8c-2baa10081bc5.png)

**Comment by johnbent** [comment]
More info from @gregnsk 👍 

curl -X GET "https://10.230.255.16:28100/api/v1/auditlogs/show/s3?start_date=1607500000&end_date=1607549999" -H "accept: application/json" -H "authorization: Bearer c71593052dfe426b9c1ec61036088230"

[
  "a9202d6a64d94fa1ac6b6d09a902ae2b84390e4557004d19b4a471cd2525f429 gtbucket1 [10/Dec/2020:00:07:53 +0530]172.16.1.78 847912992506 47b522c3-0bfe-4214-bb58-0bc843235daf REST.GET.BUCKETLOCATION gtbucket1/ GET /gtbucket1?location HTTP/1.1200 - 136 0 6666 - aws-cli/2.1.7 Python/3.7.3 Linux/3.10.0-1127.el7.x86_64 exe/x86_64.centos.7 prompt/off command/s3api.get-bucket-location  -SigV4 - AuthHeader 172.16.8.16",
  "f191c3c1fe654072abfbf1bcba0a0ae626d5fb429ef44574a12882c906814f39 gtbucket [10/Dec/2020:00:07:41 +0530]172.16.1.78 847912992506 85e639c7-40ca-4897-a9a9-c1cb83781a8b REST.GET.BUCKETLOCATION gtbucket/ GET /gtbucket?location HTTP/1.1403 AccessDenied 0 0 6969 - aws-cli/2.1.7 Python/3.7.3 Linux/3.10.0-1127.el7.x86_64 exe/x86_64.centos.7 prompt/off command/s3api.get-bucket-location  -SigV4 - AuthHeader 172.16.8.16"
]

Don't forget to run curl -X POST "https://10.230.255.16:28100/api/v1/login" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"username\": \"Administrator\", \"password\": \"Seagate@1\"}" before

**Comment by Saumya-Sunder** [comment]
Done here in this PR https://github.com/Seagate/cortx-management-portal/pull/236
