### ISSUE TITLE
Miniprovisioning templates populates csm/conf directory.

### ISSUE THREAD

**Issue by udayan-y21** [Seagate/cortx-manager#572]
Miniprovisioning templates currently populates csm/conf directory. 
https://github.com/Seagate/cortx-manager/tree/main/csm/conf
![image](https://user-images.githubusercontent.com/66424882/125440209-bc894774-7a6d-4331-864c-d6041c821a59.png)

Make a provision to put it in another directory and copy it to csm/conf directory at the time of build generation

**Comment by johnbent** [comment]
Testing.  Please ignore this comment that johnbent made in the github issue.

**Comment by balajiramachandran-seagate** [comment]
Testing. Please ignore this comment that balajiramachandran-seagate made in the github issue.

**Comment by balajiramachandran-seagate** [comment]
Testing. Please ignore this comment that balajiramachandran-seagate made in the github issue.

**Comment by cortx-admin** [comment]
> Udayan Yaragattikar commented in Jira Server:

Ready for review

**Comment by cortx-admin** [comment]
> Udayan Yaragattikar commented in Jira Server:

Resolved

**Comment by cortx-admin** [comment]
> Udayan Yaragattikar commented in Jira Server:

verified
