### ISSUE TITLE
Invalid System Name in Cortx Onboarding

### ISSUE THREAD

**Issue by hseow-seagate** [Seagate/cortx-manager#650]
In the [Onboarding Guide](https://github.com/Seagate/cortx/blob/main/doc/Preboarding_and_Onboarding.rst) number 2, an image is shown to enter "**opensource ova**" as System Name. However, it seems that any name with spaces are considered invalid.

Is there any reason for such validations? If so, perhaps the image should be changed?

**Comment by cortx-admin** [comment]
> Board-Genius-Jira commented in Jira Server:

stale commented in Github:

This issue/pull request has been marked as `needs attention` as it has been left pending without new activity for 4 days. Tagging @mukul-seagate11 for appropriate assignment. Sorry for the delay & Thank you for contributing to CORTX. We will get back to you as soon as possible.

**Comment by cortx-admin** [comment]
> Board-Genius-Jira commented in Jira Server:

hessio commented in Github:

Hi @kupranay do you know the answer to this or at least able to direct me to someone who does know the answer?

**Comment by cortx-admin** [comment]
> Board-Genius-Jira commented in Jira Server:

stale commented in Github:

This issue/pull request has been marked as `needs attention` as it has been left pending without new activity for 4 days. Tagging @mukul-seagate11 for appropriate assignment. Sorry for the delay & Thank you for contributing to CORTX. We will get back to you as soon as possible.

**Comment by hessio** [comment]
I think issue can be closed? @hseow-seagate are you ok with me closing this issue? Please reopen if you feel this issue needs to be open but I think this is no longer an issue

**Comment by hseow-seagate** [comment]
Yep, I don't think this is part of the setup anymore

**Comment by cortx-admin** [comment]
> Pawan Kumar Srivastava commented in Jira Server:

NA

**Comment by cortx-admin** [comment]
> Pawan Kumar Srivastava commented in Jira Server:

Project cancelled

**Comment by cortx-admin** [comment]
> Pawan Kumar Srivastava commented in Jira Server:

Project cancelled
